apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ .Values.service.name }}-discovery
spec:
  ports:
    - port: 9042
  selector:
    app: {{ template "fullname" . }}
