# Default values for cassandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/google-samples/cassandra
  tag: v12
  pullPolicy: Always
service:
  name: cassandra
resources:
  limits:
    cpu: "500m"
    memory: 1Gi
  requests:
    cpu: "500m"
    memory: 1Gi
